<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <AssemblyName>TestOfClaudeGen.Core.BT.Calc</AssemblyName>
    <RootNamespace>TestOfClaudeGen.Core.BT.Calc</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\X.Proto.Framework.v5\X.Proto.Common.ServiceConnector\X.Proto.Common.ServiceConnector.csproj" />
    <ProjectReference Include="..\..\X.Proto.Framework.v5\X.Proto.Common.Endpoints.Invoker\X.Proto.Common.Endpoints.Invoker.csproj" />
    <ProjectReference Include="..\..\X.Proto.Framework.v5\X.Proto.Component.Patterns.ChainResponsibility\X.Proto.Component.Patterns.ChainResponsibility.csproj" />
    <ProjectReference Include="..\..\X.Proto.Framework.v5\X.Proto.Component.Patterns.Multiplexor\X.Proto.Component.Patterns.Multiplexor.csproj" />
    <ProjectReference Include="..\..\X.Proto.Framework.v5\X.Proto.Db.Api\X.Proto.Db.Api.csproj" />
    <ProjectReference Include="..\..\X.Proto.Framework.v5\X.Proto.Db.Component.ManyToMany\X.Proto.Db.Component.ManyToMany.csproj" />
  </ItemGroup>

</Project>
