<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>TestOfClaudeGen.Endpoint.UserStudio</AssemblyName>
    <RootNamespace>TestOfClaudeGen.Endpoint.UserStudio</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\X.Proto.Framework.v5\X.Proto.Common.Endpoints.Invoker.RabbitMQ\X.Proto.Common.Endpoints.Invoker.RabbitMQ.csproj" />
    <ProjectReference Include="..\..\X.Proto.Framework.v5\X.Proto.Common.Endpoints.Setup.Autofac\X.Proto.Common.Endpoints.Setup.Autofac.csproj" />
    <ProjectReference Include="..\..\X.Proto.Framework.v5\X.Proto.Common.Endpoints.Setup.ConfigFiles\X.Proto.Common.Endpoints.Setup.ConfigFiles.csproj" />
    <ProjectReference Include="..\..\X.Proto.Framework.v5\X.Proto.Common.Events\X.Proto.Common.Events.csproj" />
    <ProjectReference Include="..\Core.User\Core.User.csproj" />
    <ProjectReference Include="..\Core.User.Jobs\Core.User.Jobs.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Update="CONFIGS\appconfig.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Update="CONFIGS\autofac.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>
